### ISSUE TITLE
I would like if Polymorph could be added to the pack

### ISSUE THREAD

**Issue by Tim-Odermatt** [AmmoniumX/Forever-Factory#1]
**Is your feature request related to a problem? Please describe.**
When I created Quark Chests and I want to Craft them into normal Chest again, it prioritizes the Drawer Recipe instead of the Vanilla Chest.

**Describe the solution you'd like**
Adding https://www.curseforge.com/minecraft/mc-mods/polymorph would make a Recipe be able to change the output of the Recipe

**Describe alternatives you've considered**
None

**Additional context**
https://github.com/illusivesoulworks/polymorph/issues/197

Sadly there is a bug in Polymorph 1.19.2

not sure if this is Fixable for the Crafting Station.

**Comment by AmmoniumX** [comment]
You don't need Polymorph to do this. You can craft quark chests into regular chests.

Additionally, Polymorph _is_ in the pack. It just doesn't work with most modded crafting menus (like the crafting station), you need a vanilla crafting table
