### ISSUE TITLE
[BUG] Crafting job never completes when you start pulling items out of Integrated Dynamics network storage.

### ISSUE THREAD

**Issue by Yuuva124** [AmmoniumX/Forever-Factory#12]
**Environment (please complete the following information):**
 - OS: Windows
 - Launcher: Prism Launcher
 - Modpack Version: 1.0.7

**Describe the bug**
![2024-12-06_12 16 34](https://github.com/user-attachments/assets/70570d3f-f6ef-4938-a027-49737e0ad2f0)
As long as the Create Funnel under the barrel isn't doing anything, the Fluid Encapsulator to the left continuously makes Treated Wood Planks. As soon as I tell the Funnel to start dropping the planks, the Encapsulator will finish making the plank it was working on, then stop, and the crafting job will never be considered complete. The network storage still has more than enough ingredients to keep crafting.
![2024-12-06_12 23 25](https://github.com/user-attachments/assets/fb1e8a63-c779-424e-bed9-0cd18f4f1b73)
In this setup, as long as the conveyor belt is constantly pulling Treated Planks out of the network before they can really enter the barrel, the Encapsulator constantly works. If the belt isn't pulling planks at all and they build up in the barrel, the Encapsulator constantly works. If the belt is pulling items, then I stop the belt and the items start building up in the barrel, it keeps working. If I then start up the belt again and begin pulling items out of the barrel, the Encapsulator stops and the crafting job never completes. Same as the smaller setup, there's still plenty of ingredients.

**To Reproduce**
1. Setup a crafting interface and writer with Treated Wood Planks recipe for the Fluid Encapsulator.
2. Give the network wood and creosote and let it start crafting while filling the storage.
3. Start pulling the Treated Planks out of the network storage.

**Expected behavior**
The Encapsulator should keep running as it still has more ingredients to use.

**Comment by AmmoniumX** [comment]
This repository is for stuff regarding specific content in Forever Factory, including custom recipe changes, items, and quest content. Your problem seems related to Integrated Dynamics, so you should probably report it to them instead:
https://github.com/CyclopsMC/IntegratedDynamics/issues

**Comment by AmmoniumX** [comment]
> Sorry. Mod author said ask the modpack author first.
Where are you talking to the mod author? If it's on discord, I wouldn't mind joining the conversation so the three of us can properly figure out the problem. Keep me updated pls

**Comment by Yuuva124** [comment]
I just sent an issue report on github, and he has seen it. I'll let you know if we move to discord to figure it out.

**Comment by Yuuva124** [comment]
We figured out the problem. The version of Common Capabilities the modpack is currently using appears to be the problem. After updating to the newest version, the problem went away.
