### ISSUE TITLE
Could you add "Fuelgoeshere" to the pack?

### ISSUE THREAD

**Issue by Tim-Odermatt** [AmmoniumX/Forever-Factory#2]
**Is your feature request related to a problem? Please describe.**
When shift Clicking Coal/Charcoal into a Furnace it Prioritizes the upper Slot, which creates Graphite.
Most of the times when i Shift Click Coal into a Furnace i Want it inside the Fuel SLOT.

**Describe the solution you'd like**
Add the Mod https://www.curseforge.com/minecraft/mc-mods/fuelgoeshere

**Describe alternatives you've considered**
None

**Additional context**
![image](https://github.com/user-attachments/assets/68f1b9af-b1d3-4d36-bce3-38e336fc9b8e)

**Comment by AmmoniumX** [comment]
added
