### ISSUE TITLE
[BUG] Enigmatica Crushed Zinc cannot be Washed for Gunpowder

### ISSUE THREAD

**Issue by Bereim** [AmmoniumX/Forever-Factory#3]
**Describe the bug**
Create Crushed Zinc can be washed for a chance at Gunpowder, but Emendatus Enigmatica Crushed Zinc cannot.

**Expected behavior**
Both Crushed Ores should have valid Washing Recipes.

**Comment by AmmoniumX** [comment]
Fixed in 1.0.6
