### ISSUE TITLE
[BUG] Not possible to craft most blocks from CC:C Bridge

### ISSUE THREAD

**Issue by logicallysound** [AmmoniumX/Forever-Factory#6]
**Environment (please complete the following information):**
 - Modpack Version: 1.0.4

**Describe the bug**
The Source Block, Target Block, and Scroller Pane from the ComputerCraft:Create Bridge mod included in the pack cannot be crafted because Asurine doesn't generate in the world.

**Expected behavior**
Make it possible to acquire Asurine or change the recipes to accept another material that can be acquired.

**Comment by AmmoniumX** [comment]
Fixed in 1.0.6
