### ISSUE TITLE
[BUG] Unable to make Oil Sand

### ISSUE THREAD

**Issue by Syphus590-863** [AmmoniumX/Forever-Factory#7]
**Environment (please complete the following information):**
 - Modpack Version 1.0.5

**Describe the bug**
Unable to make Oil Sand because recipe requires Thermal Series Crude Oil and it is impossible to get it.

**Expected behavior**
Make the Oil Sand recipe accept #forge:crude_oil

**Comment by AmmoniumX** [comment]
Already fixed in https://github.com/AmmoniumX/Forever-Factory/commit/3ad865ab89add72b6bd61321239af5eae22f56b0 , will be published in next version
