### ISSUE TITLE
[BUG]Unable to complete quest Ch V "(Extreme) Reactor" due to misconfigured item

### ISSUE THREAD

**Issue by Syphus590-863** [AmmoniumX/Forever-Factory#8]
**Environment (please complete the following information):**
 - Modpack Version 1.0.6

**Describe the bug**
Ch V "(Extreme) Reaktor" Quest requires item "emendatusenigmatica:uranium_ingot" however when you smelt raw uranium bought from the shop you get "immersiveengineering:ingot_uranium". Therefore there is no way to complete the quest.

**Expected behavior**
Change quest requirements or smelting recipe

**Comment by AmmoniumX** [comment]
Are you playing on server by any chance? Because the 1.0.6 server pack had this issue but it was fixed on 1.0.6b, so please download the 1.0.6b server pack and update with it
