### ISSUE TITLE
[BUG] Blaze Burner with Straw is not recognized as a heat source for PneumaticCraft

### ISSUE THREAD

**Issue by Amadeus99** [AmmoniumX/Forever-Factory#9]
**Environment (please complete the following information):**
 - OS: Windows
 - Launcher GDLauncher Carbon
 - Modpack Version 1.0.6

**Describe the bug**
Blaze Burner with Straw is not recognized as a heat source for PneumaticCraft.

**To Reproduce**
1. Place down a Blaze Burner.
2. Place a PneumaticCraft Heat Pipe next to the Blaze Burner.  The Heat Pipe will connect to the burner.
3. Right-click a Straw on the Blaze Burner.  The Heat Pipe will disconnect from the Blaze Burner. (Using a Heat Pipe was a clear and easy way to see that the Blaze Burner with Straw does not support PneumaticCraft heat.)
4. A fueled normal Blaze Burner will cause the temperature to rise in a Refinery Controller but a fueled Blaze Burner with Straw will not.

**Expected behavior**
A Blaze Burner with Straw should provide heat to PneumaticCraft machines just like a normal Blaze Burner does.

**Comment by AmmoniumX** [comment]
This was already added in a576fc594e9794ebdfb08fc013bb0ed4fff35e65 and will come out on the next modpack update

**Comment by Amadeus99** [comment]
Thanks.  =)
